"""Build reproducible, attributed seed records from approved public sources."""
from __future__ import annotations

import asyncio
import io
import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

import httpx

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
UA = "GeographyLearningAgent/0.1 (local educational prototype; source snapshots)"

# title | category | aliases: sources are fetched, not generated by a model.
TOPICS = """
Oceanic climate|climate|temperate oceanic climate;marine west coast climate;maritime climate
Mediterranean climate|climate|Mediterranean climates
Tropical rainforest climate|climate|equatorial climate
Tropical monsoon climate|climate|
Tropical savanna climate|climate|savanna climate
Humid subtropical climate|climate|
Humid continental climate|climate|
Subarctic climate|climate|
Tundra climate|climate|
Ice cap climate|climate|
Desert climate|climate|arid climate
Semi-arid climate|climate|semiarid climate;steppe climate
Climate|climate|
Weather|climate|
Climate change|climate|
Global warming|climate|
Greenhouse effect|climate|
Greenhouse gas|climate|greenhouse gases
Precipitation|climate|
Rain shadow|climate|rain shadows
Monsoon|climate|monsoons
Trade winds|climate|trade wind
Westerlies|climate|prevailing westerlies
Atmospheric circulation|climate|
Intertropical Convergence Zone|climate|ITCZ
El Niño|climate|El Nino
La Niña|climate|La Nina
Tropical cyclone|climate|tropical cyclones
Humidity|climate|
Albedo|climate|
Köppen climate classification|climate|Koppen climate classification
Continental climate|climate|
Orographic lift|climate|orographic rainfall
Ocean current|physical|ocean currents
Gulf Stream|physical|
North Atlantic Current|physical|North Atlantic Drift
Thermohaline circulation|process|
Latitude|concept|
Longitude|concept|
Equator|physical|
Prime meridian|concept|
Tropic of Cancer|physical|
Tropic of Capricorn|physical|
Arctic Circle|physical|
Antarctic Circle|physical|
Hemispheres of Earth|concept|Northern Hemisphere;Southern Hemisphere;Eastern Hemisphere;Western Hemisphere
Map projection|concept|map projections
Contour line|concept|contour lines
Scale (map)|concept|map scale
Geographic information system|concept|GIS;geographic information systems
Remote sensing|concept|
Plate tectonics|process|
Continental drift|process|
Subduction|process|
Seafloor spreading|process|sea-floor spreading
Earthquake|process|earthquakes
Volcano|landform|volcanoes
Erosion|process|
Weathering|process|
Sediment transport|process|
Deposition (geology)|process|deposition
Water cycle|process|hydrological cycle;hydrologic cycle
Evaporation|process|
Condensation|process|
Transpiration|process|
Infiltration (hydrology)|process|infiltration
Surface runoff|process|runoff
River|landform|rivers
Drainage basin|landform|watershed;catchment area;drainage basins
River delta|landform|deltas;river deltas
Estuary|landform|estuaries
Meander|landform|meanders
Oxbow lake|landform|oxbow lakes
Floodplain|landform|floodplains
Waterfall|landform|waterfalls
Glacier|landform|glaciers
Fjord|landform|fjords
U-shaped valley|landform|glacial trough
Mountain|landform|mountains
Plateau|landform|plateaus;plateaux
Plain|landform|plains
Desert|landform|deserts
Sand dune|landform|sand dunes;dune;dunes
Karst|landform|
Coast|landform|coastline;coasts
Peninsula|landform|peninsulas
Archipelago|landform|archipelagos
Island|landform|islands
Coral reef|landform|coral reefs
Atoll|landform|atolls
Biome|concept|biomes
Ecosystem|concept|ecosystems
Biodiversity|concept|
Tropical rainforest|landform|tropical rainforests
Savanna|landform|savannas
Tundra|landform|
Taiga|landform|boreal forest
Deforestation|process|
Desertification|process|
Urbanization|human|urbanisation
Population density|human|
Human migration|human|migration
Demographic transition|human|
Natural resource|human|natural resources
Sustainable development|human|
Renewable energy|human|
Agriculture|human|
Irrigation|human|
Nile|physical|Nile River;River Nile
Amazon River|physical|River Amazon
Amazon rainforest|physical|Amazon Rainforest
Sahara|physical|Sahara Desert
Himalayas|physical|Himalaya
Andes|physical|Andes Mountains
Alps|physical|
Rocky Mountains|physical|Rockies
Mount Everest|physical|Everest
Pacific Ocean|physical|
Atlantic Ocean|physical|
Indian Ocean|physical|
Arctic Ocean|physical|
Southern Ocean|physical|
Mediterranean Sea|physical|
Great Barrier Reef|physical|
Lake Victoria|physical|
Lake Baikal|physical|
Yangtze|physical|Yangtze River
Ganges|physical|Ganges River
Mississippi River|physical|
Congo River|physical|
Danube|physical|Danube River
Rhine|physical|Rhine River
Democratic Republic of the Congo|country|DR Congo;DRC
Republic of the Congo|country|Congo-Brazzaville
Georgia (country)|country|
Georgia (U.S. state)|place|State of Georgia
Africa|physical|
Europe|physical|
Asia|physical|
North America|physical|
South America|physical|
Antarctica|physical|
Oceania|physical|
Australia (continent)|physical|Australian continent
Middle East|physical|
Southeast Asia|physical|
Central Asia|physical|
East Asia|physical|
Western Europe|physical|
East Africa|physical|
""".strip()

STUDY = {
    "Oceanic climate": {
        "definition": "A climate with relatively mild summers and cool winters, a small annual temperature range, and precipitation throughout the year. Nearby oceans help moderate temperatures.",
        "features": ["Moderate seasonal temperature differences", "Rainfall in all seasons", "Common on western coasts in middle latitudes"],
        "examples": ["Parts of western Europe, including the British Isles", "Parts of New Zealand"],
        "question": {"prompt": "Which pattern best describes an oceanic climate?", "options": ["Mild temperatures with rainfall throughout the year", "Hot summers and almost no rain in any season", "Very cold winters with a large annual temperature range"], "answer": 0, "feedback": "The ocean moderates temperature, and precipitation occurs throughout the year."},
    },
    "Mediterranean climate": {
        "definition": "A climate characterized by dry summers and wetter winters. It occurs in several regions around the world, not only around the Mediterranean Sea.",
        "features": ["Dry summers", "Wetter winters"],
        "question": {"prompt": "When is rainfall usually greater in a Mediterranean climate?", "options": ["Summer", "Winter", "It never rains"], "answer": 1, "feedback": "Mediterranean climates characteristically have wetter winters and dry summers."},
    },
    "Latitude": {
        "definition": "The angular distance of a location north or south of the Equator, measured in degrees. The Equator is at 0° latitude.",
        "question": {"prompt": "What does latitude measure?", "options": ["Distance east or west of the prime meridian", "Angular distance north or south of the Equator", "Height above sea level"], "answer": 1, "feedback": "Latitude measures north–south position relative to the Equator."},
    },
    "Longitude": {"definition": "The angular distance east or west of a reference meridian, usually the prime meridian at Greenwich, measured in degrees."},
    "Plate tectonics": {"definition": "The theory that Earth's outer rigid layer is divided into plates that move relative to each other. Their interactions help explain earthquakes, volcanoes, and mountain building."},
    "Erosion": {"definition": "The removal and transport of rock, soil, or other surface material by agents such as water, wind, or ice.", "question": {"prompt": "How does erosion differ from weathering?", "options": ["Erosion involves removal and transport", "Erosion only breaks rock in place", "Erosion only happens underground"], "answer": 0, "feedback": "Weathering breaks material down in place; erosion removes and transports it."}},
    "Weathering": {"definition": "The breakdown or alteration of rocks and minerals at or near Earth's surface. Unlike erosion, weathering does not itself require transport of the material."},
    "Water cycle": {"definition": "The continuous movement of water between the atmosphere, land, and oceans through processes including evaporation, condensation, precipitation, and runoff.", "question": {"prompt": "Which process changes liquid water into water vapour?", "options": ["Condensation", "Evaporation", "Infiltration"], "answer": 1, "feedback": "Evaporation changes liquid water into water vapour."}},
    "Rain shadow": {"definition": "A relatively dry area on the sheltered side of a mountain range. Rising air often loses moisture on the windward side, leaving drier air on the leeward side."},
    "Population density": {"definition": "The number of people living in a unit of area, often expressed as people per square kilometre.", "question": {"prompt": "A region has 1,000 people in 10 km². What is its population density?", "options": ["10 people/km²", "100 people/km²", "10,000 people/km²"], "answer": 1, "feedback": "Divide population by area: 1,000 ÷ 10 = 100 people/km²."}},
}

RELATIONS = {
    "Oceanic climate": [("North Atlantic Current", "associated with"), ("Westerlies", "influenced by"), ("Mediterranean climate", "compare with")],
    "Erosion": [("Weathering", "compare with"), ("Sediment transport", "involves")],
    "Weathering": [("Erosion", "compare with")],
    "Water cycle": [("Evaporation", "includes"), ("Condensation", "includes"), ("Precipitation", "includes"), ("Surface runoff", "includes")],
    "Latitude": [("Equator", "measured from"), ("Longitude", "compare with")],
    "Plate tectonics": [("Subduction", "includes"), ("Earthquake", "helps explain"), ("Volcano", "helps explain")],
    "River": [("Meander", "may form"), ("River delta", "may form"), ("Drainage basin", "drains")],
    "Mediterranean climate": [("Oceanic climate", "compare with")],
}

def key(title):
    return "wiki:" + title

async def main():
    DATA.mkdir(exist_ok=True)
    date = datetime.now(timezone.utc).isoformat()
    records = []
    async with httpx.AsyncClient(timeout=35, headers={"User-Agent": UA}, follow_redirects=True) as client:
        url = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson"
        r = await client.get(url)
        r.raise_for_status()
        world = r.json()
        (DATA / "world.geojson").write_text(json.dumps(world), encoding="utf-8")
        country_names = {f["properties"]["ISO_A2_EH"]: f["properties"]["ADMIN"] for f in world["features"] if f["properties"].get("ISO_A2_EH")}
        for feature in world["features"]:
            p = feature["properties"]
            name = p.get("ADMIN", p["NAME"])
            if name in ("Antarctica", "Georgia", "Democratic Republic of the Congo", "Republic of the Congo"):
                continue
            aliases = {name, p.get("NAME_LONG", ""), p.get("NAME", "")}
            if name == "United Kingdom": aliases |= {"UK", "Britain"}
            if name == "United States of America": aliases |= {"United States", "USA", "U.S.A.", "US"}
            if name == "Czechia": aliases.add("Czech Republic")
            if name == "Turkey": aliases.add("Türkiye")
            if name == "Ivory Coast": aliases.add("Côte d'Ivoire")
            lat, lon = p.get("LABEL_Y"), p.get("LABEL_X")
            pop, year = p.get("POP_EST"), p.get("POP_YEAR")
            records.append({
                "id": "country:" + p["ADM0_A3"], "title": name, "aliases": sorted(a for a in aliases if a), "category": "country",
                "definition": f"{name} is in {p['CONTINENT']}, in the {p['SUBREGION']} region according to Natural Earth's classification.",
                "features": [], "examples": [], "relations": [], "question": None,
                "facts": [{"label": "Continent", "value": p["CONTINENT"]}, {"label": "Region", "value": p["SUBREGION"]}] + ([{"label": f"Population estimate ({year})", "value": f"{int(pop):,}", "year": year}] if pop and year and year > 0 else []),
                "location": {"lat": lat, "lon": lon, "kind": "Representative point", "zoom": 4, "geometry_code": p["ADM0_A3"]} if lat is not None and lon is not None else None,
                "sources": [{"title": "Natural Earth — Admin 0 Countries", "url": "https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/", "license": "Public domain", "retrieved_at": date, "revision": "repository snapshot", "data_url": url}],
                "origin": "local", "review_status": "source-derived", "version": "1", "excerpt": "", "excerpt_label": "",
            })
        topics = [line.split("|") for line in TOPICS.splitlines()]
        for offset in range(0, len(topics), 15):
            batch = topics[offset:offset+15]
            response = await client.get("https://en.wikipedia.org/w/api.php", params={"action": "query", "format": "json", "formatversion": 2, "prop": "extracts|coordinates|info|revisions|pageprops", "inprop": "url", "exintro": 1, "explaintext": 1, "exlimit": 20, "rvprop": "ids|timestamp", "redirects": 1, "titles": "|".join(t[0] for t in batch)})
            response.raise_for_status()
            query = response.json().get("query", {})
            redirects = {x["from"]: x["to"] for x in query.get("redirects", []) + query.get("normalized", [])}
            pages = {p["title"]: p for p in query.get("pages", [])}
            for title, category, alias_text in batch:
                resolved = title
                for _ in range(4): resolved = redirects.get(resolved, resolved)
                page = pages.get(resolved)
                if not page or "missing" in page or "disambiguation" in page.get("pageprops", {}):
                    print("Skipped", title)
                    continue
                excerpt = page.get("extract", "").strip()
                if not excerpt:
                    print("No extract", title)
                    continue
                # Snapshot excerpt: bounded display, attributed under Wikipedia's licence.
                excerpt = " ".join(excerpt.split()[:180])
                study = STUDY.get(title, {})
                coords = page.get("coordinates", [])
                rev = page.get("revisions", [{}])[0]
                aliases = [title] + ([x.strip() for x in alias_text.split(";") if x.strip()])
                if title == "Georgia (country)": aliases = ["Georgia (country)"]
                records.append({
                    "id": key(title), "title": title.replace(" (geology)", "").replace(" (hydrology)", "").replace("Scale (map)", "Map scale"), "aliases": aliases, "category": category,
                    "definition": study.get("definition", excerpt), "features": study.get("features", []), "examples": study.get("examples", []), "facts": [],
                    "relations": [{"id": key(t), "title": t, "label": label, "source_url": page.get("fullurl")} for t, label in RELATIONS.get(title, [])],
                    "question": study.get("question"),
                    "location": {"lat": coords[0]["lat"], "lon": coords[0]["lon"], "kind": "Representative point", "zoom": 4} if coords else None,
                    "sources": [{"title": "Wikipedia — " + page["title"], "url": page.get("fullurl", "https://en.wikipedia.org/wiki/" + quote(page["title"].replace(" ", "_"))), "license": "CC BY-SA 4.0 (see article history)", "retrieved_at": date, "revision": str(rev.get("revid", "")), "revision_at": rev.get("timestamp"), "wikidata_id": page.get("pageprops", {}).get("wikibase_item")}],
                    "origin": "local", "review_status": "editorial review pending" if study else "source excerpt", "version": "1", "excerpt": excerpt, "excerpt_label": "Wikipedia excerpt" if not study else "Study guide; adapted from the linked source",
                })
            print("Fetched topics", min(offset+15, len(topics)), "/", len(topics))
        # GeoNames: select the most populous cities; population reference years are absent, so omit population.
        response = await client.get("https://download.geonames.org/export/dump/cities15000.zip")
        response.raise_for_status()
        rows = zipfile.ZipFile(io.BytesIO(response.content)).read("cities15000.txt").decode("utf-8").splitlines()
        cities = sorted((row.split("\t") for row in rows), key=lambda row: int(row[14] or 0), reverse=True)[:70]
        for row in cities:
            name, country = row[1], row[8]
            country_name = country_names.get(country, country)
            definition = f"{name} is a populated place in {country_name}." + (" GeoNames classifies it as a national capital." if row[7] == "PPLC" else "")
            records.append({"id": "geonames:" + row[0], "title": name, "aliases": list(dict.fromkeys([name, row[2]])), "category": "place", "definition": definition, "features": [], "examples": [], "facts": [{"label": "Country", "value": country_name}, {"label": "Time zone", "value": row[17]}], "relations": [], "question": None, "location": {"lat": float(row[4]), "lon": float(row[5]), "kind": "Place location", "zoom": 10}, "sources": [{"title": "GeoNames — " + name, "url": "https://www.geonames.org/" + row[0], "license": "CC BY 4.0", "retrieved_at": date, "revision": row[18]}], "origin": "local", "review_status": "source-derived", "version": "1", "excerpt": "", "excerpt_label": ""})
    ids = {r["id"] for r in records}
    for record in records:
        record["relations"] = [rel for rel in record["relations"] if rel["id"] in ids]
    (DATA / "knowledge.json").write_text(json.dumps(records, indent=2, ensure_ascii=False), encoding="utf-8")
    print("Saved", len(records), "records")

if __name__ == "__main__":
    asyncio.run(main())
